version: '3.8'

services:
  bobapp-back:
    build: ./back
    container_name: bobapp-back
    ports:
      - "8080:8080"

  bobapp-front:
    build: ./front
    container_name: bobapp-front
    ports:
      - "4200:80"
    depends_on:
      - bobapp-back
