name: Build Java + Angular

on:
  push:
    branches: [ main, feature/ci-cd ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test-back:
    runs-on: ubuntu-latest
    name: Run back-end tests
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with coverage and SonarCloud (back-end)
        working-directory: back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=CelineIntha_P10_CI-CD \
            -Dsonar.organization=celineintha \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Upload JUnit test report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: back/target/surefire-reports/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/

  test-front:
    runs-on: ubuntu-latest
    name: Run front-end tests
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run tests with coverage
        run: |
          cd front
          npm ci
          npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: front/coverage/

  test-report:
    name: Test reporting summary
    needs: [ test-back, test-front ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download JUnit report
        uses: actions/download-artifact@v4
        with:
          name: junit-report
          path: reports/junit

      - name: Publish JUnit test results
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Tests Summary
          path: reports/junit/*.xml
          reporter: java-junit
          fail-on-error: false

  sonarcloud-front:
    name: Analyze front-end with SonarCloud
    runs-on: ubuntu-latest
    needs: [ test-front ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd front
          npm ci

      - name: Run SonarCloud scanner for front-end
        working-directory: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=celineintha-p10-ci-cd-front \
            -Dsonar.organization=celineintha \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=src \
            -Dsonar.tests=src \
            -Dsonar.test.inclusions=**/*.spec.ts \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
